### ISSUE TITLE
Cannot resolve latest version from private Azure Artifacts package source

### ISSUE THREAD

**Issue by patros** [jerriep/dotnet-outdated#105]
Like issue #42 maybe?

If I add a package source credentials entry it works. But I'd prefer not have credentials in my nuget.config and be able to make use of https://github.com/Microsoft/artifacts-credprovider which is what the standard dotnet commands make use of.

Let me know if there is anything I can do to help troubleshoot this. i.e. configure a test feed, etc

**Comment by jerriep** [comment]
@patros Looking at the readme on the GH repo you linked to, this seems like a fairly recent addition to how NuGet handles user authentication. 

In any case, feel free to look into it if you want. My available time for working on issues in this repo is limited at the moment.

**Comment by patros** [comment]
No worries @jerriep

I'll try to debug this and figure out what needs to happen.

**Comment by ransagy** [comment]
I have opened a PR to add basic support for this scenario https://github.com/jerriep/dotnet-outdated/pull/199

**Comment by ransagy** [comment]
This has been merged in the latest release. Feel free to test and close @patros :]

**Comment by patros** [comment]
Great work @ransagy

**Comment by scabana** [comment]
Hi, just tried it. It wasn't working for me, giving this error: ```Errors occurred while analyzing dependencies for some of your projects. Are you sure you can connect to all your configured NuGet servers?```. Took a look into the code and found out this: https://github.com/NuGet/NuGet.Client/blob/eb135ec42a4b04c5a87f7938755fe02b37da01c8/src/NuGet.Core/NuGet.Protocol/Plugins/PluginFactory.cs#L168, on my system ```DOTNET_HOST_PATH``` is not set for some reason. I don't know what should have set it to begin with. Seems to work if you set it with "dotnet", but I'm sure I'll be in trouble for this later :)

**Comment by scabana** [comment]
@ransagy seems like something might be missing for this one: https://github.com/NuGet/Home/issues/7438#issuecomment-434402124 seems like it's expected to be set by the caller.

**Comment by ransagy** [comment]
Hah. Now that you mentioned it, I did come across this, but not in this tool, rather a different one that does some NuGety things as well. I didn't find any particular helpful response to why not - https://github.com/NuGet/Home/issues/7438
