### ISSUE TITLE
Support detecting outdated transitive dependencies

### ISSUE THREAD

**Issue by DamianEdwards** [jerriep/dotnet-outdated#13]
Love this tool! It would be even better if it supported detecting outdated dependencies of my dependencies (transitive dependencies).

E.g. detect that *My.Great.Lib* which is transitively referenced is not using the latest version:
```
- App
   |- Foo.Bar/1.2 (latest version is 1.2)
      |- My.Great.Lib/1.0 (latest version is 1.1)
```

**Comment by jerriep** [comment]
Yeah, this one would be great. I just need to figure out how to tell MS Build to generate the dependency graph to include all those transitive dependencies as well...

But I actually need to figure that out in any case for another tool I had in mind 😉

**Comment by jerriep** [comment]
Some notes:

During restore, a `project.assets.json` file is created. This stores the complete graph of the actual dependencies which were restored. Maybe we can piggy-back on this?

Use this search to try and discover more: https://github.com/search?utf8=%E2%9C%93&q=org%3Adotnet+%22project.assets.json%22&type=Code

**Comment by jerriep** [comment]
Also see https://natemcmaster.com/blog/2017/12/21/netcore-primitives/

Piggybacking off of the `*.deps.json` could be an option

**Comment by jerriep** [comment]
@DamianEdwards  Version 1.1.0 is avaliable on NuGet and it adds this feature

**Comment by DamianEdwards** [comment]
Nice!!
