### ISSUE TITLE
support .fsproj

### ISSUE THREAD

**Issue by jrr** [jerriep/dotnet-outdated#17]
`dotnet outdated` accepts:
- directory containing a .sln
- .sln file
- directory containing a .csproj
- .csproj file

it does not currently accept:
- directory containing .fsproj
- .fsproj file

It should! (PR incoming)

Interestingly, it will happily pick up a .fsproj from a .sln.

**Comment by jerriep** [comment]
@jrr Version 1.1.0 is available on NuGet and it adds this feature. Thanks again for your PR!
