### ISSUE TITLE
Complaining about the nuget servers

### ISSUE THREAD

**Issue by screig** [jerriep/dotnet-outdated#173]
We have an internal repo. I'm not sure if that's the issue, but something seems to be wrong, the following CLI call detects the new package:

`dotnet list package --outdated`

![image](https://user-images.githubusercontent.com/4292074/60341445-72bb2900-99a6-11e9-863e-e5d95d346b7a.png)

but the **dotnet outdated** call fails.

**Comment by screig** [comment]
Downgrading to version 2.2.0 fixed this

**Comment by jerriep** [comment]
All I can suggest is that you download the code, run it inside VS code and see whether you can somehow debug this. 

There is no way I can possibly debug this against your internal nuget server.

If you're willing to do that, please open a PR. If you are not, then please close this issue.
