### ISSUE TITLE
Updated nugets from private repo not shown

### ISSUE THREAD

**Issue by abbotware** [jerriep/dotnet-outdated#188]
Seems like a regression may have happened as this seemed to be a previous issue.

I am using a solution with a nuget.config file. if I open a command prompt in the root of the solution and type:
`dotnet list package --outdated`
i see my nuget updates from a private Nexus OSS repo.  Also works fine from Visual Studio

if a type:
`dotnet-outdated `

it only lists updates from nuget.org and not the private feed

**Comment by abbotware** [comment]
I downloaded the source and am running it - it appears to list the feed correctly in the code: GetEnabledSources - no exception is thrown - so not sure where it is going wrong yet...

**Comment by abbotware** [comment]
Looks like a simple fix - see the PR - I will be testing the upgrade functionality to see if there are any issues with code

**Comment by abbotware** [comment]
I can confirm that filtering and upgrading the nugets works :-) 

I'll be using a private build so no rush on the merge!

**Comment by jerriep** [comment]
Closed with #189
