### ISSUE TITLE
Error running from CI Tools (Window Service)

### ISSUE THREAD

**Issue by abbotware** [jerriep/dotnet-outdated#190]
It appears that I can't run dotnet-outdated from a CI Tool / Windows Service (GoCD specifically).  

The script I have written works fine from the command prompt, but fails with the error message:

```
Upgrading package Core...
An error occurred while upgrading Core

```

Since this is running as a windows service, its a lot harder to attempt to recreate and debug... is there any way I can get diagnostics to see what the 'error' was?

**Comment by abbotware** [comment]
it seems that I am no longer getting this error! :-)

**Comment by jerriep** [comment]
Yeah. sadly there is no proper way to diagnose issues like these. I need to add more verbose logging in cases like this
