### ISSUE TITLE
Update readme for newest Net Core

### ISSUE THREAD

**Issue by ysangkok** [jerriep/dotnet-outdated#222]
I tried various ways of running the tool, but I can't get it to work. It is confusing that the screenshot is showing syntax that is apparently no longer valid?

```
 % dotnet tool install --global dotnet-outdated
Tool 'dotnet-outdated' is already installed.
 % dotnet tool list                            
Package Id      Version      Commands      Manifest
---------------------------------------------------
 % dotnet tool run outdated                
Cannot find a tool in the manifest file that has a command named 'outdated'.
 % dotnet tool run --global outdated
Cannot find a tool in the manifest file that has a command named '--global'.
 % dotnet outdated                  
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-outdated does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by jerriep** [comment]
I have never tried this with .NET Core 3.x, so it likely does not support a scenario where you only have it and not 2.x installed.

If you want to update it to support 3.x, I am happy to accept a PR, as long as you maintain backward compatibility to 2.x

**Comment by ahryshchanka** [comment]
PR #225 created

but please merge first #226 , this implementation depends on ##227 and #226 and will be better to close this in the end, after others (I suppose it will be merged without problems)

**Comment by jerriep** [comment]
v2.7.0 now supports .NET SDK 3.0
