### ISSUE TITLE
Question: depguard-alike for .NET

### ISSUE THREAD

**Issue by christophwille** [jerriep/dotnet-outdated#223]
I might have missed the obvious, but I haven't found a .NET equivalent of Go's depguard - https://github.com/OpenPeeDeeP/depguard (if you know of such a build task/tool/VS extension please let me know; OWASP & Snyk do also scan dependencies, but again for different purposes)

Given that dotnet-outdated does scan transitive packages, would be building such a functionality on top of its implementation a proper idea? (I would have suggest adding it if the tool name weren't -outdated)

**Comment by jerriep** [comment]
From what I understand from the description of depguard, this is not something that fits into the scope of this tool and thus does not make sense to add it

I would suggest looking through this [list of .NET Global tools](https://github.com/natemcmaster/dotnet-tools) to see whether there is already something that does this. If not, you can attempt to build it yourself.

A lot of the functionality of dotnet-outdated is contained in a standalone Nuget package (see source here https://github.com/jerriep/dotnet-outdated/tree/master/src/DotNetOutdated.Core), so feel free to use that it possible

**Comment by christophwille** [comment]
@jerriep fyi https://github.com/christophwille/dotnet-depguard
