### ISSUE TITLE
Fails to regnonize project as .Net Core

### ISSUE THREAD

**Issue by Orgbrat** [jerriep/dotnet-outdated#23]
Decided to try the tool but on my first try I am getting the below error and not sure what is happening as the is a ASP.NET Core 2.1 project.. Any ideas?

PM> dotnet tool install --global dotnet-outdated
You can invoke the tool using the following command: dotnet-outdated
Tool 'dotnet-outdated' (version '1.0.0') was successfully installed.
PM> dotnet-outdated
dotnet-outdated : Unable to process the the project `D:\Work - VS.NET 2018\ASP.NET21\Orgbrat.Blog-v2.1\src\OrgbratBlog.sln. Are you sure this is a valid .NET Core or .NET Standard project type?
At line:1 char:1
+ dotnet-outdated
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to proce...d project type?:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

Here is the full error message returned from the Microsoft Build Engine:

Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: -

For switch syntax, type "MSBuild /help"

**Comment by jerriep** [comment]
Any chance you can post the `.sln` and `.csproj` files here? No need for the actual source code files...

**Comment by Orgbrat** [comment]
No problem here they are..

[src.zip](https://github.com/jerriep/dotnet-outdated/files/2072922/src.zip)

**Comment by jerriep** [comment]
@Orgbrat The issue was related to the space on your actual path name. Internally, **dotnet-outdated** runs MSBuild and passes it the full path to your project. The problem was that I did not cater for paths with spaces in them, so MSBuild saw it as separate parameters and therefore the _Unknown switch_ error message.

I fixed this by ensuring the path is surrounded by quotes and the update will be in the next release.

If you are eager to get your hand on it now, you can install the pre-release as follows:

```
dotnet tool install -g dotnet-outdated --version 1.1.0-pre.36 --add-source https://www.myget.org/F/jerriep/api/v3/index.json
```

Be sure to uninstall the existing version first though:

```
dotnet tool uninstall -g dotnet-outdated
```

**Comment by jerriep** [comment]
@Orgbrat  Version 1.1.0 is available on NuGet and it solves this problem.

**Comment by davidcarson** [comment]
Might be more space-related issues. I'm getting "Are you sure this is a valid .NET Core or .NET Standard project type?" for every project I throw at it, with this MSBuild error:

`MSBUILD : error MSB1008: Only one project can be specified.`
`Switch: Carson\AppData\Local\Temp\tmpAFA9.tmp`

My Windows username is "David Carson" so the temp file path is `C:\Users\David Carson\AppData\Local\Temp\tmpAFA9.tmp` - I suspect that is being passed unquoted to MSBuild.

**Comment by jerriep** [comment]
@davidcarson Thank you for reporting this. The fix will be in `v1.3.0`. If you are in a hurry to try it out, you can install the pre-release version from MyGet using the following command:

```text
dotnet tool install -g dotnet-outdated --version 1.3.0-pre.70 --add-source https://www.myget.org/F/jerriep/api/v3/index.json
```

**Comment by davidcarson** [comment]
@jerriep works perfectly now, you're a champion!

**Comment by jerriep** [comment]
Great stuff! Thanks for your work on identifying the underlying issue.

**Comment by jerriep** [comment]
@davidcarson Version 1.3.0 is now available with the fix for this.

**Comment by alexdresko** [comment]
Still happening 

```
PS C:\code\stark\SOLO> dotnet-outdated --version
A .NET Core global tool to list outdated Nuget packages.
2.6.0-rtm.339+a0ee49b274fc9f266f409bc14114671151589454
```

```
PS C:\code\stark\SOLO> dotnet-outdated
Analyzing project and restoring packages...Unable to process the project `C:\code\stark\SOLO\src\Stark.Solo.Web\Stark.Solo.Web.csproj. Are you sure this is a valid .NET Core or .NET Standard project type?

Here is the full error message returned from the Microsoft Build Engine:

Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by jerriep** [comment]
@alexdresko Are you sure that that project is in fact a .NET SDK project?

Can you post the .csproj file here?
