### ISSUE TITLE
Feature request: I want dotnet-outdated to fail if the new version of the package is older than X days

### ISSUE THREAD

**Issue by bdn-mca** [jerriep/dotnet-outdated#236]
We are using dotnet-outdated in our CI pipeline as it is a great tool for DevSecOps to ensure we have our nuget packages in the project always up to date.

However, there are some packages that have new updates almost on daily basis, and it slows down development and breaks all our CI builds - so  the development team needs to urgently react on every single update.

Is there a problem in adding a new flag, say -t, which would fail the build only if the update is older than -t days?
What this will do is let the developers finish their job and update the packages on their own pace.

Another CI build will be scheduled weekly to inform developers of new packages, and they will react accordingly. (other companies/users might find their own protocol of using this flag).

Also, some companies do not feel comfortable jumping directly on the newest versions, as they might contain some bugs, and might want to wait for some time before updating to the newest pacakge.

**Comment by jerriep** [comment]
Hi Boris, this sounds like a useful feature, but it is not something I have the time to implement now. If you want to take a stab at implementing it, I would be happy to accept a pull request.

**Comment by jerriep** [comment]
Added in #237
