### ISSUE TITLE
Add support for NuGet credential providers

### ISSUE THREAD

**Issue by tillig** [jerriep/dotnet-outdated#255]
NuGet supports the ability to [use credential providers](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin) like the [Azure Artifacts credential provider](https://github.com/Microsoft/artifacts-credprovider) when working with secure feeds. This allows people to not have username/password entries in nuget.config.

It would be nice to have that support in `dotnet outdated` as well.

I found [this gist](https://gist.github.com/cpyfferoen/74092a74b165e85aed5ca1d51973b9d2#file-nugetmanager-cs-L49) that supposedly adds this sort of support, but I don't know if it helps.

**Comment by jerriep** [comment]
The believed that #199 resolved this. Have you tried using the Azure Artifacts Credentials provider?

**Comment by tillig** [comment]
Yeah, I can `dotnet restore` and such using the provider, but `dotnet outdated` reports it had trouble accessing those feeds. It's what prompted me to file the issue.

Are there diagnostic logs or something I can provide?

I'm on a Mac, unsure if that matters for the location algorithm.

**Comment by jerriep** [comment]
Unfortunately, I do not use Azure Artifacts, so this is not something I can test. Also, there are no proper diagnostics logs you can turn on :(

Maybe you can clone the dotnet-outdated repo and run it inside the debugger against your project to try and debug the underlying issue. Since I do not use Azure Artifacts and don't have a Mac, this is not something I can really debug myself.

If you can locate the issue and fix it, I will be happy to accept a PR from you

**Comment by tillig** [comment]
OK, let me see what I can do.

**Comment by tillig** [comment]
Research update:

I added a temporary `ConsoleLogger` to the credential setup line:

```c#
DefaultCredentialServiceUtility.SetupDefaultCredentialService(new ConsoleLogger(), true);
```

Stupid simple logger just to get some information out.

```c#
using System;
using System.Threading.Tasks;
using NuGet.Common;

namespace DotNetOutdated
{
    public class ConsoleLogger : LoggerBase
    {
        public ConsoleLogger() : this(LogLevel.Verbose)
        {
        }

        public ConsoleLogger(LogLevel verbosityLevel) : base(verbosityLevel)
        {
        }

        public override void Log(ILogMessage message)
        {
            Console.WriteLine("[{0:u}|{1}] {2}", message.Time, message.Level, message.Message);
        }

        public override Task LogAsync(ILogMessage message)
        {
            this.Log(message);
            return Task.CompletedTask;
        }
    }
}
```

That logs some info that points to the issue:

```
[2020-01-28 22:02:37Z|Debug] Using /Users/tillig/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll as a credential provider plugin.
[2020-01-28 22:02:37Z|Error] Problem starting the plugin '/Users/tillig/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll'. Cannot start process because a file name has not been provided.
[2020-01-28 22:02:37Z|Debug] System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at NuGet.Protocol.Plugins.PluginProcess.Start()
   at NuGet.Protocol.Plugins.PluginFactory.CreatePluginAsync(String filePath, IEnumerable`1 arguments, IRequestHandlers requestHandlers, ConnectionOptions options, CancellationToken sessionCancellationToken)
   at NuGet.Protocol.Plugins.PluginFactory.GetOrCreateAsync(String filePath, IEnumerable`1 arguments, IRequestHandlers requestHandlers, ConnectionOptions options, CancellationToken sessionCancellationToken)
   at NuGet.Protocol.Plugins.PluginManager.TryCreatePluginAsync(PluginDiscoveryResult result, OperationClaim requestedOperationClaim, PluginRequestKey requestKey, String packageSourceRepository, JObject serviceIndex, CancellationToken cancellationToken)
```

You get more information with the 5.4.0 versions of the NuGet libraries than 5.1.0. which is what the project currently references. However, the upgrade doesn't fix anything so I rolled back that bump.

I'm still trying to figure out what that means exactly. It appears that while the credential provider plugin is _found_, it's not able to _execute_, which explains why `dotnet outdated` isn't able to auth to my Azure Artifacts feed.

**Comment by tillig** [comment]
I figured it out. [It's this issue.](https://github.com/NuGet/Home/issues/7438)

The [`PluginFactory` assumes there's an environment variable `DOTNET_HOST_PATH`](https://github.com/NuGet/NuGet.Client/blob/0ba1a97052d9ba3f581bab5ab173270dac6681f0/src/NuGet.Core/NuGet.Protocol/Plugins/PluginFactory.cs#L168) set, but there's not.

In PowerShell Core, I can do this:

```powershell
[System.Environment]::SetEnvironmentVariable("DOTNET_HOST_PATH", "/usr/local/share/dotnet/dotnet")
```

With that, `dotnet outdated` works fine. If you're using that `ConsoleLogger` then you actually see a lot more logging about the provider connecting to Azure Artifacts and checking dependency versions.

It appears this was also a source of challenge in #105.

Unclear what a good solution here is. The error isn't in the `dotnet outdated` command, but it's hard to debug what's going on.

I might suggest:

- Add a "known issues" section to the README with an explanation of how to resolve this (by adding the missing env var).
- If there are errors to report, do a check at that time for `DOTNET_HOST_PATH` - if it's not there, write out a warning that it should be added.

It's not a perfect solution, but it'd help folks get past the unexpected error.

I'd be happy to PR that error/reporting thing if you'd like.

**Comment by jerriep** [comment]
Thank you for the analysis @tillig 

My time is limited at the moment, so if you want to create a PR as suggested, I will appreciate it

**Comment by tillig** [comment]
[PR submitted.](https://github.com/jerriep/dotnet-outdated/pull/264)
