### ISSUE TITLE
[Proposal] Option to list packages even when the latest version is installed

### ISSUE THREAD

**Issue by mrmartan** [jerriep/dotnet-outdated#257]
This might be the reverse of what was done previously but I am looking for a way to report on all used packages (across a large number of project), sometimes not only those that need updating. `dotnet list package` would be ideal for that if it had some machine friendly output. Unfortunately it does not while `dotnet-outdated` does.

I might be able to do a PR if that is desirable. I suppose it would be just about adding and option and skipping some filtering step.

**Comment by jerriep** [comment]
I understand the temptation to just add this option as it is _so close_ to what this tool already does, but simply listing installed NuGet packages is outside of the scope of this tool. The purpose of this tool is to list and update **outdated** packages.

I think it is best to address this by maybe creating another tool. The core functionality of this project is available as a library which you are free to use in another tool. I will also be amenable to making changes to that core library to suit your purposes for a tool like this (if it does not already suit your purposes)

**Comment by mrmartan** [comment]
What libraty is that? Do you mena the `DotnetOutdated.Core`?

**Comment by jerriep** [comment]
Yes

**Comment by mrmartan** [comment]
AFAICT the reporting fuctionality is in the `DotnetOutdated` package anyway. So unless you would want to refactor that I am OK with forking this and building my own version. I am installing and using the tool from Docker image in CI/CD anyway so I don't care whether it comes from nuget.org repository or elsewhere.

Could you perhaps just point me where would be best to amend the tool to report all packges instea of just outdated ones, please?
