### ISSUE TITLE
NuGet packages without dependencies are not resolved 

### ISSUE THREAD

**Issue by n-sidorov** [jerriep/dotnet-outdated#27]
If NuGet package does not have any dependencies declared `dotnet-outdated` cannot resolve it's version.

Example of such packages are Roslyn Analyzers (like https://www.nuget.org/packages/Microsoft.NetCore.Analyzers).

Example of output with Analyzers referenced in project
![image](https://user-images.githubusercontent.com/3368120/41907705-96da704a-7939-11e8-9f11-c6ac4f50bb68.png)

**Comment by jerriep** [comment]
Issue seems to be stemming from packages which does not contain actual library files, e.g.

![image](https://user-images.githubusercontent.com/1006420/42360722-ccbc62a8-8114-11e8-9ec6-81ffc92faf64.png)

and 

![image](https://user-images.githubusercontent.com/1006420/42360742-e0d73c18-8114-11e8-94b2-947a6f9bc348.png)

So, when I check to see whether the package can be installed into the current framework, my check does not take this into account.
