### ISSUE TITLE
Tool requires 2.1.0

### ISSUE THREAD

**Issue by steveoh** [jerriep/dotnet-outdated#280]
I updated to .net core sdk 3.1.2 and cleared out all other versions and this tool no longer runs. Can we update it to work on dotnet core 3 without affecting 2 users?

```
dotnet outdated
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.2 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.15-x64
```

**Comment by jerriep** [comment]
Hi @steveoh 

Support for .Net Core 3.0 (alongside 2.1) was added a few months ago in version 2.7. I am not sure whether 3.0 would work with 3.1, but until explicit support for 3.1 is added, please try the following:

1. Uninstall your version of `dotnet-outdated` and try and see whether you can install the latest version which has support for 3.0
1. If you cannot do that, please install the 3.0 SDK as an interim measure and then try and install `dotnet-outdated` again.

When I have time, I will add support for `netcoreapp3.1`.

**Comment by steveoh** [comment]
Oh yes I have updated since your version 2.2.0 oops ;)
