### ISSUE TITLE
Support parseable output

### ISSUE THREAD

**Issue by shatl** [jerriep/dotnet-outdated#29]
Please add option to display packages in easy to parse format.

I'm looking to use dotnet-outdated to generate reports which can be further processed by scripts.

Ideally it should produce plain text similar to this:
`Project;Package;CurrentVersion;Status;LatestVersion`

where _Status_ is Current or Outdated

Also depends on #28

P.S. Thanks for a great tool

**Comment by patros** [comment]
@jerriep I'd be happy to have a go at this one too.

Based on the JSON output from PR #100...
`Project.Name;TargetFramework.Name;Dependency.Name;Dependency.ResolvedVersion;Dependency.LatestVersion;Dependency.UpgradeSeverity`?

**Comment by jerriep** [comment]
Closed by #103
