### ISSUE TITLE
Colors not displaying correctly on iTerm on macOS

### ISSUE THREAD

**Issue by jerriep** [jerriep/dotnet-outdated#3]
The second third column should display some of the items in blue. Not showing up correctly on iTerm on macOS:

<img width="1082" alt="screen shot 2018-05-17 at 12 46 38" src="https://user-images.githubusercontent.com/1006420/40158750-5c64c7d6-59d0-11e8-9b2f-5b2d60ca7cf9.png">

**Comment by mattwoberts** [comment]
I'm on OSX, and I see the colors (zsh in item):

![image](https://user-images.githubusercontent.com/109196/40182708-e89c88ca-59e3-11e8-8ee8-871bebe3b59f.png)

**Comment by jerriep** [comment]
Issue was related to my iTerm color scheme which had an override for the default terminal colors.
