### ISSUE TITLE
Can't install without specifying version

### ISSUE THREAD

**Issue by OskarKlintrot** [jerriep/dotnet-outdated#30]
Not sure what is going on or if it is intended or not but I couldn't install this without specifying the version. I do have a private nuget feed in my global `package.json`, could that be the issue?

```
D:\> dotnet tool install --global dotnet-outdated
C:\Program Files\dotnet\sdk\2.1.300\NuGet.targets(114,5): error : Unable to load the service index for source https://<my company>.pkgs.visualstudio.com/DefaultCollection/_packaging/<private project>/nuget/v3/index.json. [C:\Users\oskkli\AppData\Local\Temp\ve2re1lo.gay\restore.csp
roj]
C:\Program Files\dotnet\sdk\2.1.300\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\oskkli\AppData\Local\Temp\ve2re1lo.gay\restore.csproj]
The tool package could not be restored.
Tool 'dotnet-outdated' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
D:\> dotnet tool install --global dotnet-outdated --version 1.2.0
You can invoke the tool using the following command: dotnet-outdated
Tool 'dotnet-outdated' (version '1.2.0') was successfully installed.
```

**Comment by jerriep** [comment]
The current version is not a pre-release:
https://www.nuget.org/packages/dotnet-outdated

Looking at the error output it seems to rather be a case that your Nuget configuration is wrong. it is trying to install from the Nuget source `https://<my company>.pkgs.visualstudio.com/DefaultCollection/_packaging/<private project>/nuget/v3/index.json`, which I assume is one of your own projects, right?

Please run the following command from that same directory that you tried to install `dotnet-outdated`:

```
nuget sources
```

Tell me what the output of this command is.

**Comment by OskarKlintrot** [comment]
```
D:\> nuget sources
Registered Sources:

  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  <private project> [Enabled]
      https://<my copmpany>.pkgs.visualstudio.com/DefaultCollection/_packaging/<private project>/nuget/v3/index.json
  3.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

**Comment by jerriep** [comment]
Your sources seem to be correct. It could also be that you perhaps have issues connecting from your computer to the Nuget website. 

This problem is however not anything I have control over. You will have to ask on either the Nuget or .NET Core CLI repositories for assistance.

**Comment by OskarKlintrot** [comment]
Just tried to install another dotnet tool, same issue.
