### ISSUE TITLE
Can't upgrade projects with `RestoreLockedMode`

### ISSUE THREAD

**Issue by foriequal0** [jerriep/dotnet-outdated#313]
It would be better to have an option to pass `--no-restore` to `dotnet add` command. I can do `dotnet restore --force-evaluate` later then.

**Comment by jerriep** [comment]
Hi @foriequal0, can you please expand on the issue. I am not familiar with `RestoreLockedMode` and what the effects of that is and how this is creating problems for you.

**Comment by foriequal0** [comment]
I lock versions of package references using `RestorePackagesWithLockFile` flag that creates `packages.lock.json` on restoring. It holds resolved exact versions of packages while package references declare ranges of versions.

I always can restore exact same versions of packages with my local dev environment in the CI/CD environment since restoring tries to use the lock file to get exact versions of packages. There is less possibility of 'It works for me!' since it is the same version here and there.

Except when I upgraded package but I don't commit `packages.lock.json`.

`RestoreLockedMode` ensures that `packages.lock.json` is derived from package references in the `csproj` file. It makes sure that they don't diverge by failing the restoring.

Here's the problem: `dotnet add` modifies package references first, and tries to restore after. Restoring fails because the lock file is not updated simultaneously.

I think `dotnet add` should be fixed eventually. They should do like `dotnet restore --force-evaluate` rather than just `dotnet restore`, but it would take too long. They just put it in the backlog and the ice age would come.

There is an escape hatch in their `dotnet add`: `dotnet add --no-restore`. It literally makes `dotnet add` doesn't do restore after updating package references. I can do `dotnet restore --force-evaluate` to forcefully update `package.lock.json`. It is a valid move since I intended to upgrade packages, so the lock file should be updated.

**Comment by jerriep** [comment]
Ok, thank you for the clarification. So I think the best would be to add a `--no-restore` option for `dotnet-outdated`, in which case it will call `dotnet add` with the `--no-restore` option.

I do not have much time to spend on this project at the moment. If you want to take a stab at it and submit a PR, I would be happy to accept it
