### ISSUE TITLE
Support updating package references in Directory.Build.props

### ISSUE THREAD

**Issue by jnm2** [jerriep/dotnet-outdated#319]
It's common for me to specify analyzers that I want to apply to all projects in the solution using Directory.Build.props. (See https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build#directorybuildprops-and-directorybuildtargets.)

When `dotnet outdated -u` runs, it produces "An error occurred while upgrading" for each project in the solution. What I'd expect is for it to unify to a single Directory.Build.props file update.

A typical Directory.Build.Props:

```xml
<Project>

  <PropertyGroup>
    <Product>A</Product>
    <Version>B</Version>
    <Company>C</Company>
    <Copyright>D</Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Features>strict</Features>
    <TreatWarningsAsErrors Condition="'$(Configuration)' != 'Debug'">True</TreatWarningsAsErrors>
    <EmbedAllSources>true</EmbedAllSources>
    <AllowedReferenceRelatedFileExtensions>.pdb</AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetAnalyzers.DocumentationAnalyzers" Version="1.0.0-beta.59" PrivateAssets="all" />
    <PackageReference Include="ReflectionAnalyzers" Version="0.1.21-dev" PrivateAssets="all" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.164" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

**Comment by jnm2** [comment]
Also, this is reminiscent of a direction that the SDK is taking with the [Directory.Packages.props first-class feature](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions).

**Comment by jerriep** [comment]
@jnm2 Under the covers, `dotnet-outdated` simply calls the `dotnet add package` command to upgrade the packages. So support for something like this is dependent on the .NET Core SDK. Once they add support for it, which it seems that will be doing if I read the document you linked to above correctly, then `dotnet-outdated` can support it as well

**Comment by jnm2** [comment]
Thanks!

**Comment by jerriep** [comment]
@jnm2 You're welcome to keep this issue open if you want, so it can be confirmed that it works when the SDK adds support for it. There just won't be any movement on it until then.

**Comment by jnm2** [comment]
Cool. I'm fine waiting until I know there's a problem, but feel free to reopen if you want to use this as a tracking issue to confirm that it works.
