### ISSUE TITLE
PackageReference duplicated on MSBuild projects

### ISSUE THREAD

**Issue by wwdenis** [jerriep/dotnet-outdated#329]
## Issue
When trying to upgrade a Classic .NET project (msbuild), the entry `PackageReference` is duplicated instead of being updated.

## Steps to Reproduce

![MSBUILD_DUPLICATED](https://user-images.githubusercontent.com/21691662/83015874-665da700-a021-11ea-9152-2e1b7edeb530.gif)

## Foo.csproj

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <RootNamespace>Foo</RootNamespace>
    <AssemblyName>Foo</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <OldToolsVersion>4.0</OldToolsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Sentry" Version="1.0.0" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

## Technical Information
- dotnet version 3.1.100
- Windows 10 Pro Build 18363.836

**Comment by jerriep** [comment]
Under the hood, dotnet-outdated simply runs the `dotnet add package` command.

What happens when you run `dotnet add package Sentry -v 2.1.1` directly against your project?

**Comment by wwdenis** [comment]
> Under the hood, dotnet-outdated simply runs the `dotnet add package` command.
> 
> What happens when you run `dotnet add package Sentry -v 2.1.1` directly against your project?

Same issue @jerriep (do not remove the old reference)
I believed the `--upgrade` parameter would call `dotnet remove package` then `dotnet add package`

There's a way to achieve this in the current version?

**Comment by jerriep** [comment]
Leaving the old package reference in place is not normal behaviour. This is the first time that I have heard of this behaviour you are describing.

Explicitly removing and then re-adding the package is not currently possible with `dotnet-outdated` and I see no reason to change the behaviour to work this way based on one isolated incident. Even the .NET Core CLI documentation states that calling `dotnet add package` is the correct way to update a package:
https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli#update-a-package

As far as I am concerned, this is a problem with the .NET Core CLI, so I am going to ask you to file a bug report with them over here:
https://github.com/dotnet/sdk
