### ISSUE TITLE
The command name in installer message is confusingly

### ISSUE THREAD

**Issue by wcoder** [jerriep/dotnet-outdated#37]
## Steps to reproduce

- execute `dotnet tool install --global dotnet-outdated`
- after success install: ![](https://user-images.githubusercontent.com/766193/42362051-256c08c4-80fa-11e8-9954-53037d5066cb.png)
- `dotnet-outdated` - command not found, because used command `dotnet outdated`

**Comment by jerriep** [comment]
This is not an issue. Well, at least not on my side. That message is printed by the .NET Core CLI. From my side, the instructions in the readme file makes it very clear that you need to run the command using the `dotnet outdated` command.

Regarding that message, you will need to raise an issue on the [.NET Core CLI repo](https://github.com/dotnet/cli).
