### ISSUE TITLE
Only first nuget source from nuget.config is used

### ISSUE THREAD

**Issue by skolima** [jerriep/dotnet-outdated#38]
It's quite common to have both a public feed url and a private in-org repository configured - however, dotnet-outdated will only check the first source configured.

That's because https://github.com/jerriep/dotnet-outdated/blob/master/src/DotNetOutdated/Services/NuGetPackageInfoService.cs#L55 doesn't allow for multiple sources to be used.

**Comment by skolima** [comment]
yeah, ignore me please

**Comment by jerriep** [comment]
No worries. It should work with all the configured sources. If you find a case where it doesn't, please let me know.
