### ISSUE TITLE
Cannot resolve latest version from private Nuget package source 

### ISSUE THREAD

**Issue by dmagnanimo** [jerriep/dotnet-outdated#42]
I am using a private server that stores a variety of nuget packages and i noticed
the problem described in the title above.
Digging through your source code i noticed that the method `GetAllVersions ` inside `NuGetPackageInfoService` does not add to the return, versions coming from the object of type **PackageSearchMetadataV2Feed** how can i resolve this?

**Comment by jerriep** [comment]
Please give me more information on what sort of private feed this is. Where is it hosted?

**Comment by dmagnanimo** [comment]
The server where my nuget packages are hosted, is a Windows Server 2016, v1607

**Comment by jerriep** [comment]
But how is it hosted? What sort of NuGet server are you using?

**Comment by dmagnanimo** [comment]
I am using the latest version of this library: https://github.com/joelverhagen/NuGet.Server

**Comment by jerriep** [comment]
OK, will look into it when I get a chance

**Comment by thoemmi** [comment]
I experience the same issue with AppVeyor feeds, e.g. the feed for GitVersion packages https://ci.appveyor.com/nuget/gitversion-8nigugxjftrw

I already have a solution and will create a PR.

**Comment by jerriep** [comment]
Version 2.0.0 is now available on NuGet which resolves this issue:
https://www.nuget.org/packages/dotnet-outdated/2.0.0

Thanks for the PR @thoemmi
