### ISSUE TITLE
Show what part of the version number has changed

### ISSUE THREAD

**Issue by tlycken** [jerriep/dotnet-outdated#45]
Thanks for an awesome tool!

I think it could be even cooler, if it stole some ideas from e.g. `yarn outdated`. This is my output from there:

![image](https://user-images.githubusercontent.com/1550920/42574713-5b66cf12-851f-11e8-8b09-3f494295c7cf.png)

Note how the different colors indicate whether this is a major, minor or patch update, and makes it clear which components of the version number have changed.

`dotnet outdated` could improve on the current format by showing, e.g. outdated version number part on the currently installed version in red, and the latest version of those parts in blue (and up-to-date packages in green as currently).

What do you think, would this be a good idea? How difficult would it be to implement?

**Comment by jerriep** [comment]
Yeah, I like indicating whether it is a major, minor or patch upgrade with the colors. I am busy reworking the output display at the moment to also be in a table format as in your picture, so I will look into adding the colors as well

**Comment by jerriep** [comment]
I decided to simply indicate with the color whether this is a major, minor, or patch upgrade. I think that info is enough to highlight to the user whether they should be cautious about updating a package.

![image](https://user-images.githubusercontent.com/1006420/42796609-5b1cc012-89b5-11e8-8b94-b415aadbc107.png)

**Comment by tlycken** [comment]
That's a big improvement! But I really do think there's merit in coloring different parts of the version number differently, too. Maybe if you're done with your display code overhaul I could take a stab at it in a PR?

**Comment by jerriep** [comment]
Yeah, sure.

**Comment by jerriep** [comment]
@tlycken I did a quick test and I actually find it more difficult to read that way. In my opinion, the change in colour causes the brain to pauses for the briefest of moments which it is reading over the change in colors

![image](https://user-images.githubusercontent.com/1006420/42805725-c81b5ce8-89d6-11e8-8cb0-b7b67de7f301.png)

I think the simple red/yellow/green is enough to indicate to the user at a glance whether they should be cautious of the upgrade or not.

**Comment by tlycken** [comment]
@jerriep I colored mine slightly differently:

![image](https://user-images.githubusercontent.com/1550920/42807870-3feee9e4-89b2-11e8-9b47-5d11d5f25fec.png)

I find it easier to read than both the current implementation and your quick test, but I totally get it if you don't - it doesn't surprise me at all if preference for these things is very personal. I can file a PR for this change if you want, but if you don't want it I'll refrain :)

**Comment by jerriep** [comment]
Yeah sure, I'll take that PR. Using the different colors on the version number does help, I think

Just make sure you rebase before you submit your PR, since I made a few other changes in the past hour or so. If you don't your PR will likely have merge conflicts

**Comment by jerriep** [comment]
> not sure why they are colored in your screenshot and not mine...

I changes the color for the project names (along with a few other tweaks), which is why I suggest you rebase first

**Comment by jerriep** [comment]
I like the first one best :)

**Comment by jerriep** [comment]
Looking at your second version, and my attempt, I think the problem is that is just *too* colourful. Your first attempt strikes a nice balance to not overload the screen with too many colours

**Comment by jerriep** [comment]
Version 2.0.0 is now available on NuGet which resolves this issue:
https://www.nuget.org/packages/dotnet-outdated/2.0.0

Thanks for the PR @tlycken
