### ISSUE TITLE
dotnet-outdated cannot be updated if already installed - please change that

### ISSUE THREAD

**Issue by fmorriso** [jerriep/dotnet-outdated#50]
Please update your instructions so that people do not make the following mistake:

```
dotnet-outdated --version
1.3.0-rtm .......
```
Try to update to the latest version:
```
dotnet tool install --global dotnet-outdated
Tool 'dotnet-outdated' is already installed.
```
Please update your instructions to mention that you have to perform the following command to update to the latest edition:
```
dotnet tool update --global dotnet-outdated
```

**Comment by jerriep** [comment]
@fmorriso  I have updated it for you.

Next time, please consider submitting a PR. It would have taken you about the same time as opening an issue.
