### ISSUE TITLE
v2.0.0 prints an empty line for each up-to-date dependency in ConEmu

### ISSUE THREAD

**Issue by thomaslevesque** [jerriep/dotnet-outdated#51]
This doesn't happen with the default Windows console. I think it might be due to this:

https://github.com/jerriep/dotnet-outdated/blob/f8f16f2c976633318d3a6caa77118c8131d01beb/src/DotNetOutdated/Program.cs#L384

**Comment by jerriep** [comment]
I use ConEmu (via Cmder) and do not get the sort of behaviour you are describing.

Can you post a screenshot?

**Comment by thomaslevesque** [comment]
Now I can't reproduce it anymore... It stopped after I cleared the console (using `cls`) and I can't make it happen again. I think it only happens when the console is in a certain state.

**Comment by jerriep** [comment]
I know it does weird thing sometimes when you resize the window.

Closing this for now. If you can provide reproducible steps, feel free to re-open.
