### ISSUE TITLE
Filtering of nuget packages

### ISSUE THREAD

**Issue by jepperc** [jerriep/dotnet-outdated#55]
Hi. 
Has there been any thoughts about adding a filtering parameter? I'm thinking like "dotnet test --filter sometest"
E.g. we have lots of internal nuget packages named in some way, and sometimes I would like only to upgrade those, or maybe only upgrade all microsoft packages.
"dotnet outdated --filter Microsoft.*"

**Comment by simsod** [comment]
It would also be awesome if the update parameter would take this filter. That way you could update all outdated microsoft packages for example.

**Comment by jerriep** [comment]
Closed with #72
