### ISSUE TITLE
Support for fsproj

### ISSUE THREAD

**Issue by csharpfritz** [jerriep/dotnet-outdated#90]
Love the outdated tool...  can we also use this with fsproj files?

**Comment by jerriep** [comment]
@csharpfritz This was added in bf8b63ff129f4835503cc0c663792f4063080fc6. Are you still experiencing issues with this?

**Comment by jerriep** [comment]
@csharpfritz I confirmed that F# support is working correctly. There was, however, an oversight in the help messages and readme file in that it did not explicitly mention F# support. I have corrected this.
