### ISSUE TITLE
Force update only for a specific feed

### ISSUE THREAD

**Issue by imperugo** [jerriep/dotnet-outdated#95]
Hi, 
into my nuget.config I've different feeds but I want to force the update only for one feed and not all.

Is there a way to specify the feed name to sort my issue?

Thanks

**Comment by jerriep** [comment]
No there is not. The only way to achieve this would be to update the nuget.config for the project to only reference the one feed.

**Comment by imperugo** [comment]
Hi @jerriep 
I tried this but I think it is using also main nuget feed that I don't wont to update.

Is it possible?
Thanks

**Comment by jerriep** [comment]
Yes, it is possible. You will need to explicitly tell it in your project `nuget.config` to ignore the other sources defined elsewhere by added a `<clear />` element before you declared the new sources.

See [this page](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) for more info and some examples.

**Comment by jerriep** [comment]
You may also try using the `<disabledPackageSources>` element in the document I linked to above. I have not tried it, but, reading that document, it seems like that will work as well.

**Comment by jerriep** [comment]
@imperugo I am closing this since **dotnet-outdated** simply piggy-backs on the underlying NuGet infrastructure to determine the correct NuGet feeds to use. 

For clarification you can refer to [Configuring NuGet behavior](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) which I linked to previously.

**Comment by imperugo** [comment]
Hi @jerriep 

Thanks for the support, I'll take a look to your suggestion.
